source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/deltaDNA/CocoaPods'

xcodeproj 'DeltaDNA SmartAds iOS Example'
workspace '../DeltaDNAAds'

pod 'DeltaDNAAds', :path => '../'

# Enable extra logging
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DeltaDNA' || target.name == 'DeltaDNAAds'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DDNA_DEBUG=1'
            end
        end
    end
end
