before_install:
    - gem install cocoapods
    - pod repo update
language: objective-c
osx_image: xcode8
podfile: Tests/Podfile
script:
    - xcodebuild test -workspace DeltaDNAAds.xcworkspace -scheme 'SmartAds iOS Example' -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7'
