before_install:
    - gem install cocoapods
    - pod repo update > /dev/null
language: objective-c
podfile: Podfile
xcode_workspace: DeltaDNAAds.xcworkspace
xcode_scheme: ObjC SmartAds Example
xcode_sdk: iphonesimulator
matrix:
    fast_finish: true
    include:
        - {osx_image: xcode9.2,     env: 'PLAT=iOS  DST="OS=11.2,name=iPhone 6"'}
        - {osx_image: xcode9.2,     env: 'PLAT=iOS  DST="OS=8.4,name=iPhone 6"'}

        - {osx_image: xcode9.3beta, env: 'PLAT=iOS  DST="OS=11.3,name=iPhone 6"'}
        - {osx_image: xcode9.3beta, env: 'PLAT=iOS  DST="OS=8.4,name=iPhone 6"'}

    allow_failures:
        - {osx_image: xcode9.3beta, env: 'PLAT=iOS  DST="OS=11.3,name=iPhone 6"'}
        - {osx_image: xcode9.3beta, env: 'PLAT=iOS  DST="OS=8.4,name=iPhone 6"'}

script:
    - "xcodebuild -version"
    - "set -o pipefail"
    - "xcodebuild \
        -workspace $TRAVIS_XCODE_WORKSPACE \
        -scheme \"$TRAVIS_XCODE_SCHEME\" \
        -sdk $TRAVIS_XCODE_SDK \
        -destination \"$DST\" \
        -enableCodeCoverage YES \
        -quiet \
        clean build-for-testing | xcpretty"
    - "xcodebuild \
        -workspace $TRAVIS_XCODE_WORKSPACE \
        -scheme \"$TRAVIS_XCODE_SCHEME\" \
        -sdk $TRAVIS_XCODE_SDK \
        -destination \"$DST\" \
        -quiet \
        test-without-building | xcpretty"
