before_install:
    - gem install cocoapods
language: objective-c
osx_image: xcode7.2
podfile: Tests/Podfile
script:
    - xctool test -workspace DeltaDNAAds.xcworkspace -scheme "iOS SmartAds Tests" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
